=== *Cryptocurrency and Democracy 2.0 - PART IV*

===== *_Why is all the fuss around the financial industry?_*

Financial industry provides the following four critical services to their customers:

➢    Safely storing their customers' money

➢    Providing loan to their customers for interest

➢    Offering services to transact money between different parties

➢    Playing intermediary and advisory role for investments to their customers. These customers are individuals, businesses, and governments.

In other words, financial systems are like the veins of our economy and money is like the blood. If the financial industry takes control over blood supply as well as its creation, they would be controlling and directing the blood circulation to the parts, and in directions which would be beneficial to them.

[quote, James A. Garfield, 20th president of the US]
Whoever controls the volume of money in any country is absolute master of all industry and commerce.

They can also steal certain amount of blood and contaminate the blood (inflation). The problem is not just the stolen blood but also the numerous negative effects of it. The contaminated blood impacts all organs like businesses, politics and individuals. Maybe for a while the organs believe that this is real blood, so they may work hard in their job fueled by the contaminated blood, but eventually fail. Let's see how these play in the real world in following sections.

===== *_What about the democratic systems we already have to stop the above fall?_*

The solution from the government is a central bank in most of the nations. _Federal Reserve_ (_Fed_ ) is the central bank of the US which was established in 1913.

[width="100%",cols="100%",]
|===
a|
*_Fact 1_*

Fed is not a US government organization. Fed's shares are mostly held by big banks of the world.

[.underline]##https://www.stlouisfed.org/in-plain-english/who-owns-the-federal-reserve-banks[Source:]## _Federal Reserve Bank of St. Louis_

|===

The Fed is an institution which is controlled by a few powerful private banks. It is not a government institution that controls the financial industry but [.underline]#https://www.youtube.com/watch?v=n0NYBTkE1yQ[vice versa]#.

Many central banks of the governments in the world are directly or indirectly controlled by the big private banks of the world through different means like international loans and investments. For their own benefits, politicians always employ this central banking system irrespective of big private banks' backup.

===== *_But what is the benefit for government in central banking model'_*

People love freebies, so corrupt & incompetent politicians always use this public tendency to buy votes - "Using small Fish to Catch Big Fish". To fund these freebies, governments can either use its revenue from collecting tax & tariff, or borrow money from banks and other institutions for interest (which has to be paid back to the bank using government's revenue). Raising taxes for more revenue will backfire. Banks and institutions do not give loan to a government, if they have no confidence in the government's ability to return the debt with interest. To bypass these constraints, governments allow the central banks to inflate money and give debt to the government.

With low interest rates, easy credit access and flexible financial policies, governments can control the flow of money to different industries and different classes of people, so certain wealthy people can enrich themselves at the cost of others. In this process, politicians get their cut through lobbism and corruption.

Also politicians earn huge sum of money in the name of lobbism from war profiteers - corporates and banks. How? Wars require huge amounts of weapons and goods & services from corporates. To buy them, the government requires huge amount of money for which they take inflated loans from banks.

===== *_How was the Federal Reserve created?_*

Powerful banks (power of money) and government (power of legislation) created this central bank together to control and inflate the money to provide more debt to government and others. To justify the need for a central bank in the US, government and banks accused the gold standard for the 19th century recessions. They also claimed they can control recessions by monetary control. But the root cause of most of the recessions was temporary inflation by the US government to fund the wars. To do this, the US government printed more currency with limited gold in their vaults which backfired.

To get rid of gold standard (it is hard to inflate in gold standard) completely, they also projected it as a cause of the great depression's disasters. But the root cause of the great depression was Fed's policy. The Fed made public access to credit cheaper, which accelerated the 1920s stock market bubble and then was followed by its crash in 1929. During this panic phase of the crash, the Fed again introduced another policy in which people were not allowed to withdraw money from banks, causing the economic activity to collapse further and lead to more unemployment.

But finally the power of money and legislation won, and they eventually abandoned the gold standard in 1933 by not letting people to exchange their USD for gold. After 1944, the gold exchange system was practiced in most parts of the world until the birth of the fiat money system in 1971.

[width="100%",cols="100%",]
|===
a|
	
*_Fact 2_*

As of June 30, 2011, the largest six financial institutions have assets that are the equivalent of 65 percent of US GDP (a broad measurement of a nation's overall economic activity and it is the monetary value of all the finished goods and services produced within a country's borders in a specific time period).

1. Bank of America Corp., $2.264 trillion

2. J.P. Morgan Chase & Co., $2.246 trillion

3. Citigroup Inc., $1.957 trillion

4. Wells Fargo & Co., $1.260 trillion

5. Goldman Sachs Group Inc., $937 billion

6. Morgan Stanley, $831 billion

Together, the top six companies' assets were $9.495 trillion.

[.underline]##https://www.politifact.com/truth-o-meter/statements/2011/oct/06/bernie-sanders/bernie-sanders-says-six-bank-companies-have-assets/[Source:]##__ National Information Center and U.S. Commerce Department's Bureau of Economic Analysis__

|===