=== *Cryptocurrency and Democracy 2.0 - PART III*

==== *People, Money, Financial System, Economics & Government*

===== *_Fundamental needs of people_*

[arabic]
. Good standard of living
. Healthcare
. Education
. Safer environment

And those who possess the above do not easily get exploited or suppressed by others.

===== *_Economic system to obtain these needs_*

Having an economic system that yields 100% perfect outcome for everyone at all times is not practical. But a better system that unleashes and harvests the human potential is possible and it can support the fundamental needs of people as soon as possible.

Goods and services that provide the fundamental people needs at low cost is possible only when all people work to the best of their potential. When people work at their best potential, new innovative products and services will be created that improves people's quality of life.

Both employers and employees work at their best potential only when either they are directly benefiting from their effort, or when they fear punishment from a powerful authority (so basically out of self interest or fear). The fear driven approach fails in most of the cases and in more dangerous ways. Self-interest based ecosystem has worked as a better system so far.

In real world, all this turns out like the following. More investment and larger business ecosystem leads to more number of competitively salaried jobs for more people. This also leads to more basic and innovative goods and services at low cost. This ecosystem also stops the dangers of corporate monopoly and oligopoly by letting competitive entrepreneurs fight evil corporate practices.

===== *_When and how will more investors and entrepreneurs emerge to play a role?_*

Only when an ecosystem where running businesses and trading goods and services can be conducted at low cost and without legal and illegal barriers. Simply put, when there is minimal risk and greater profit opportunity. Good infrastructure is an added advantage.

To address illegal barriers, police and defense are important for both individuals and businesses. But when one thinks about it, when we reach a scenario where most people in the world have a good standard of living, healthcare and education, there will be minimal need for police and defense.

===== *_The misplaced faith of people_*

Many people put their faith in politicians demanding them to create rules and regulations to protect from malpractices of evil corporations and dangers of criminals and terrorists. But in most of the cases, it is hard to find such honest and skilled politician who would fulfill that promise.

[quote, Lord Acton]
Power tends to corrupt; absolute power corrupts absolutely.

In reality, most politicians are corrupted with bribes and lobbyism from mobs and corporates to support them through both legal (unjust laws and regulations) and illegal means. These will cripple the confidence and effectiveness of investors and business community to succeed.

===== *_What does Cryptocurrency or any other good (sound) money have to do with the above?_*

Because a good money strictly restricts the politicians and powerful banks from engaging in the following malpractices.

●	Stealing people's hard earned money through inflation and unjust taxes

●	Spending on freebies to buy votes

●	Increasing wealth inequality in the society

●	Waging wars for profit of politicians, corporates and banks

●	Discouraging investments and business

●	Discouraging employment opportunities

●	Discouraging innovations that would have uplifted people's life

●	Creating and bending laws and regulations to favor their supporters - families, friends, party members, corporate donors and mobs

Sounds like a magic bullet?

[quote, Mayer Amschel Bauer Rothschild]
Give me control of a nation's money and I care not who makes it's laws.

There are many other greater benefits good money can offer to the world. Few of them are discussed in the upcoming sections.
